// Generated by CoffeeScript 1.4.0
(function() {
  var fixColumnHeights;

  fixColumnHeights = function() {
    if ($('html').css('content') == "\u2063") {
      $('.asset').css('height', '');

    } else {
      $('#pop').imagesLoaded(function() {
        $('.columnizer-row').each(function(idx, el) {
          $(this).find('.asset').height($(this).height());
        });
      });
    }
  };

  $(document).on('pop-initialized', function() {
    $(window).on('resize', _.throttle(fixColumnHeights));
    $('.columnizer-row .asset').live('initialize', _.throttle(fixColumnHeights));
    $('.columnizer-row .asset').live('destroy', function() {
      $(this).find('.asset').css('height', '');
    });
  });

}).call(this);
